Analysis of pilot experiment
============

```{r}
rm(list=ls())

setwd('/Users/guzmanhe/Projects/eyetracker/results/xml')
library(ggplot2)
library(stringr)
library(Gmisc)
library(plyr)
library(reshape2)
library(qgraph)
data1<-read.table("data-4+trans+seqs+transit+fixations.dat",h=T)
data1$usr_type <-factor(data1$usr_type,labels=c("mono","biling"))
data1$trial<-paste(data1$game_id,data1$id,sep = "_")
data1$region<-factor(data1$region,levels=c("divref0","divref1","divref2","divtrn0","divsrc2","divsrc1","divsrc0","start"))
levels(data1$region)<-c("Ref_prev","Ref","Ref_next","Transl","Src_next","Src","Src_prev","Out")
data1$region2<-factor(data1$region2,levels=c("divref0","divref1","divref2","divtrn0","divsrc2","divsrc1","divsrc0","end"))
levels(data1$region2)<-c("Ref_prev","Ref","Ref_next","Transl","Src_next","Src","Src_prev","Out")

data2<-subset(data1,usr_type=="biling"&game_type=="tgt" #&region %in%  c("Ref","Transl", "Src") &region2 %in%  c("Ref","Transl", "Src")  )
              )

norm<-function(x)
  {
#    return (10*( (x-min(x))/(max(x)-min(x))) +3)
    return (30*( (x)/(sum(x))) +3)

  }
plot_transition<-function(x){
   # x<-subset(x,region !="Start")
    x$region<-factor(x$region)
    x$region2<-factor(x$region2)
    
#    times<-aggregate(x$time,list("region"=x$region),sum)
    aggs<-ddply(x,c("region","region2"),summarize,"time"=length(time))
    times<-ddply(x,c("region"),summarize,"time"=sum((time+0.001)/duration))
    
    transition_mtrx <- acast(aggs,region ~region2,sum)
    groups<-factor(str_split_fixed(levels(aggs$region),"_",2)[,1])
    print(transition_mtrx)
 #   times$rel<-times$x/sum(times$x)
    transm<-transition_mtrx/sum(transition_mtrx)
    cuts=1/length(aggs$region)
    #transm<- t(apply(transition_mtrx, 1, function(x)(x/(sum(x)))))
#plot.new()
qgraph(transm,cut=cuts,esize=3,edge.width=2,asize=1.0,groups=groups,legend = F,vsize=norm(times$time),layout="groups",gray=T,vTrans=150,label.color="gray20",borders = T,directed = TRUE, diag=F)
  #  diag(transm)<-times$rel
  
}

pdf("graphs/trans-tgt-bil.pdf",width=10,height=6)
plot_transition(subset(data1,usr_type=="biling"&game_type=="tgt"))
dev.off()
pdf("graphs/trans-tgt-mono.pdf",width=10,height=6)
plot_transition(subset(data1,usr_type=="mono"&game_type=="tgt"))
dev.off()

pdf("graphs/trans-src-bil.pdf",width=10,height=6)
plot_transition(subset(data1,usr_type=="biling"&game_type=="src"))
dev.off()
pdf("graphs/trans-src-mono.pdf",width=10,height=6)
plot_transition(subset(data1,usr_type=="mono"&game_type=="src"))
dev.off()

pdf("graphs/trans-src+tgt-bil.pdf",width=10,height=6)
plot_transition(subset(data1,usr_type=="biling"&game_type=="src+tgt"))
dev.off()
pdf("graphs/trans-src+tgt-mono.pdf",width=10,height=6)
plot_transition(subset(data1,usr_type=="mono"&game_type=="src+tgt"))
dev.off()

  ```

Plot sequences


#Sanity checking
```{r}
data1$region2<-factor(data1$region,levels=c("divref0","divref1","divref2","divtrn0","divsrc2","divsrc1","divsrc0"))
levels(data1$region2)<-c("Ref_prev","Ref","Ref_next","Transl","Src_next","Src","Src_prev")


ggplot(data=subset(data1 )
                   ,aes(x=time, y=region2, group=q_type))+geom_line(alpha=0.15,type="c",aes(group=trial),col="gray",lwd=1) +geom_smooth(method="loess",n=5,aes(col=q_type),alpha=0.4,lwd=2,se=F)+facet_grid(game_type~usr_type) + theme_bw()

   opts(axis.line = theme_segment(colour = "black"),
    panel.grid.major = theme_blank(),
    panel.grid.minor = theme_blank(),
    panel.border = theme_blank(),
    panel.background = theme_blank()) 


ggplot(data=subset(data1,id %in% c("4")),aes(x=time, y=region2,group=usr_type))+geom_line(alpha=0.55,type="c",aes(group=trial,col=usr_type) )+geom_smooth(method="loess",n=10,aes(col=usr_type),alpha=0.4,lwd=1.5,se=F)+facet_grid(q_type~game_type) + theme_bw()

````